server:
  port: 8080

spring:
  application:
    name: api-gateway
    description: Servicio de enrutamiento y centralización..
    version: 1.0.0

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

  banner:
    location: classpath:banner.txt
    charset: UTF-8
    mode: console

  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
            maxAge: 3600

# JWT Configuration
app:
  jwt:
    secret: ${JWT_SECRET:E8F7D6C4B5A3F2E1D9C8B7A6F5E4D3C2B1A0F9E8D7C6B5A4F3E2D1C0B9A8F7E6D5C4B3A2F1E0D9C8B7A6F5E4D3C2B1A0F9E8D7C6B5A4}
    expiration: ${JWT_EXPIRATION:86400000}
    refresh-expiration: ${JWT_REFRESH_EXPIRATION:604800000}

# Routes Configuration
gateway:
  routes:
    auth-service:
      uri: ${AUTH_SERVICE_URL:http://auth-service:8081}
      path: /api/auth/**

    user-service-users:
      uri: ${USER_SERVICE_URL:http://user-service:8082}
      path: /api/users/**

    user-service-roles:
      uri: ${USER_SERVICE_URL:http://user-service:8082}
      path: /api/roles/**

    product-service-products:
      uri: ${PRODUCT_SERVICE_URL:http://product-service:8083}
      path: /api/products/**

    product-service-images:
      uri: ${PRODUCT_SERVICE_URL:http://product-service:8083}
      path: /images/**

    product-service-categories:
      uri: ${PRODUCT_SERVICE_URL:http://product-service:8083}
      path: /api/categories/**

    product-service-public:
      uri: ${PRODUCT_SERVICE_URL:http://product-service:8083}
      path: /api/public/products/**

    customer-service-customers:
      uri: ${CUSTOMER_SERVICE_URL:http://customer-service:8084}
      path: /api/customers/**

    order-service-orders:
      uri: ${ORDER_SERVICE_URL:http://order-service:8085}
      path: /api/orders/**

    order-service-discounts:
      uri: ${ORDER_SERVICE_URL:http://order-service:8085}
      path: /api/discounts/**

  public-paths:
    - /api/auth/login
    - /api/auth/refresh
    - /api/auth/public/register
    - /api/public/**
    - /api/customers/** # TEMPORAL: debug de clientes
    - /api/discounts/** # Administración de descuentos (proteger en producción)
    - /images/**
    - /swagger-ui/**
    - /v3/api-docs/**

# Actuator
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

# Logging
logging:
  level:
    root: INFO
    com.novacommerce: DEBUG
    org.springframework.cloud.gateway: DEBUG